#!/bin/bash

echo For a fresh install lets begin with an system update and if you wish to continue please select the appropriate option in next line.  
echo
echo Do you wish to upgrade - 'Yes' to continue and 'No' to exit the script. 
echo
read decesion
echo
if [ $decesion == "yes" ]
then 
echo
echo please choose  your 'type' of operating system and if you use any other package manager from the given below options
echo 'a = debian based linux'
echo 'b = redhat based linux'
echo 'c = arch linux'
echo 'd = opensuse'
echo 'e = gentoo'
echo 'f = flatpak'
echo
read option
   case $option in
a) apt update && apt upgrade -y;; 
b) yum update && yum upgrade -y;;
c) pacman -Syy;;
d) zypper update -y;;
e) emaint --auto sync && emerge --ask --verbose --update --deep --newuse @world ;;
f) flatpak update -y;;
g) snap refresh
 esac
echo 
echo Update complete !!
echo
else
   echo Thank you 'for' downloading the script!!
fi


